import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTypeScript from "eslint-config-next/typescript";

export default defineConfig([
  ...nextVitals,
  ...nextTypeScript,
  globalIgnores([
    ".next/**",
    ".worktrees/**",
    "coverage/**",
    // Generated by the Claude Design sync tooling and gitignored. It vendors a
    // React build whose internals trip the hook rules.
    "ds-bundle/**",
    "next-env.d.ts",
    "services/tax/**",
  ]),
]);
